import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'TR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Navigation
    'nav.home': 'Home',
    'nav.productions': 'Productions',
    'nav.marketing': 'PR & Marketing',
    'nav.academy': 'Pan Academy',
    'nav.workshops': 'Workshops',
    'nav.lessons': 'Lessons',
    'nav.about': 'About Us',
    'nav.news': 'News & Press',
    'nav.contact': 'Contact Us',
    'nav.getInvolved': 'Get Involved',
    
    // Hero Section
    'hero.slide1.title': 'Bringing Stories to Life on Stage',
    'hero.slide1.subtitle': 'Productions & Experience',
    'hero.slide1.description': 'Experience unforgettable theater productions with Pan Productions.',
    'hero.slide1.cta': 'See Upcoming Shows',
    
    'hero.slide2.title': 'Promoting Stories Beyond the Stage',
    'hero.slide2.subtitle': 'PR & Marketing',
    'hero.slide2.description': 'Our PR and marketing team ensures every production reaches the audience it deserves.',
    'hero.slide2.cta': 'Learn About Our PR Services',
    
    'hero.slide3.title': 'Empowering Creativity Through Pan Academy',
    'hero.slide3.subtitle': 'Pan Academy Workshops',
    'hero.slide3.description': 'Our workshops inspire and nurture the next generation of performers.',
    'hero.slide3.cta': 'Join a Workshop',
    
    // Index Page
    'index.whatWeOffer': 'What We Offer',
    'index.discover': 'Discover Pan Productions',
    'index.discoverDescription': 'From professional theatre productions to comprehensive drama education, we bring stories to life and nurture the next generation of performers.',
    
    'index.highlights.productions.title': 'Current Productions',
    'index.highlights.productions.description': 'Experience our acclaimed theatrical performances featuring talented casts and captivating stories.',
    'index.highlights.academy.title': 'Pan Academy',
    'index.highlights.academy.description': 'Professional workshops and lessons for actors of all levels, taught by industry experts.',
    'index.highlights.news.title': 'News & Press',
    'index.highlights.news.description': 'Stay updated with our latest news, reviews, and press coverage from the theatre world.',
    'index.highlights.exploreMore': 'Explore More',
    
    'index.whyChoose': 'Why Choose Us',
    'index.excellence': 'Excellence in Every Performance',
    'index.excellenceDescription': 'Discover what makes Pan Productions a leading name in London\'s theatre scene',
    
    'index.feature.award.title': 'Award-Winning Productions',
    'index.feature.award.description': 'Recognized for excellence with multiple theatre awards and critical acclaim',
    'index.feature.cast.title': 'Expert Cast & Crew',
    'index.feature.cast.description': 'Talented professionals with years of industry experience and passion',
    'index.feature.community.title': 'Growing Community',
    'index.feature.community.description': 'Join thousands of theatre enthusiasts and aspiring performers',
    'index.feature.passion.title': 'Passion for Theatre',
    'index.feature.passion.description': 'Dedicated to bringing powerful stories and performances to life',
    
    'index.featured': 'On Stage Now',
    'index.featuredTitle': 'Featured Productions',
    'index.featuredDescription': 'Experience our current theatrical performances',
    'index.featured.earnest.title': 'The Importance of Being Earnest',
    'index.featured.earnest.subtitle': 'A Comedy of Manners',
    'index.featured.earnest.status': 'Now Playing',
    'index.featured.earnest.description': 'Oscar Wilde\'s brilliant masterpiece returns with Pan Productions\' acclaimed cast.',
    'index.featured.workshop.title': 'Summer Theatre Workshop',
    'index.featured.workshop.subtitle': 'Intensive Drama Course',
    'index.featured.workshop.status': 'Enrolling Now',
    'index.featured.workshop.description': 'Join our immersive workshop and learn from industry professionals.',
    'index.reviews': 'Reviews',
    'index.learnMore': 'Learn More',
    'index.bookNow': 'Book Now',
    'index.viewAll': 'View All Productions',
    
    'index.testimonials': 'Testimonials',
    'index.testimonialsTitle': 'Testimonials',
    'index.testimonialsDescription': 'Hear from our audience and students about their experiences',
    'index.testimonial1.name': 'Sarah Mitchell',
    'index.testimonial1.role': 'Theatre Enthusiast',
    'index.testimonial1.content': 'Pan Productions consistently delivers outstanding performances. The attention to detail and passion of the cast is remarkable.',
    'index.testimonial2.name': 'James Wilson',
    'index.testimonial2.role': 'Workshop Student',
    'index.testimonial2.content': 'The workshops transformed my acting skills. The instructors are knowledgeable, supportive, and truly invested in your growth.',
    'index.testimonial3.name': 'Emily Thompson',
    'index.testimonial3.role': 'Regular Attendee',
    'index.testimonial3.content': 'Every production is a masterpiece. Pan Productions has become my go-to theatre company in London.',
    
    'index.cta.title': 'Ready to Experience the Magic?',
    'index.cta.description': 'Join us for an unforgettable theatrical experience. Book your tickets now or explore our workshops to start your acting journey.',
    'index.cta.bookTickets': 'Book Tickets',
    'index.cta.exploreWorkshops': 'Explore Workshops',
    
    // Newsletter
    'newsletter.title': 'Stay in the Spotlight',
    'newsletter.description': 'Get exclusive updates on upcoming productions, workshop announcements, and behind-the-scenes content delivered straight to your inbox.',
    'newsletter.placeholder': 'Enter your email address',
    'newsletter.subscribe': 'Subscribe',
    'newsletter.subscribing': 'Subscribing...',
    'newsletter.noSpam': 'No spam. Unsubscribe anytime.',
    'newsletter.success': 'Welcome to Pan Productions!',
    'newsletter.successMessage': 'You\'ve successfully subscribed to our newsletter.',
    
    // Workshops Page
    'workshops.badgeTitle': 'Pan Academy Workshops',
    'workshops.heroTitle1': 'Elevate Your',
    'workshops.heroTitle2': 'Performance Skills',
    'workshops.heroParagraph1': 'Pan Academy is a leading acting school in North London. We offer a varied range of acting classes and courses designed to suit all experience levels. Whether you\'re looking to challenge yourself, develop new skills, or take the next step in your acting journey, we have a course for you. Our evening, weekend, and part-time programs are structured to fit around your busy schedule.',
    'workshops.heroParagraph2': 'If you\'re new to acting, our Beginners Courses provide a fun and supportive environment to help you get started before progressing to Improvers and Advanced levels. For those aspiring to a professional career, our Industry Courses offer expert training to prepare you for the demands of the acting industry. If you\'re seeking an intensive experience covering a range of techniques, our Foundation in Acting course is the perfect choice.',
    'workshops.heroParagraph3': 'We offer a variety of acting courses for adults, including Acting Classes, Voice and Movement Training, along with specialized workshops such as playwriting and alongside specialised methods of acting such as Meisner, Stanislavski and Method Acting.',
    'workshops.contactUs': 'Contact Us',
    'workshops.pastWorkshopsTitle': 'Past Workshops',
    'workshops.pastWorkshopsSubtitle': 'Explore our previously held workshops that helped develop performance skills',
    'workshops.tabTheater': 'THEATER',
    'workshops.tabMusic': 'MUSIC',
    'workshops.tabArt': 'ART',
    'workshops.tabFilm': 'FILM',
    'workshops.instructor': 'Instructor',
    'workshops.completed': 'Workshop Completed',
    'workshops.noMusic': 'No music workshops available at the moment.',
    'workshops.noArt': 'No art workshops available at the moment.',
    'workshops.noFilm': 'No film workshops available at the moment.',
    'workshops.ctaTitle': 'Can\'t Find What You\'re Looking For?',
    'workshops.ctaDescription': 'We offer customized workshops and private coaching sessions. Contact us to discuss your specific training needs.',
    'workshops.requestLesson': 'Request Private Lesson',
    'workshops.feature1Title': 'Expert Instructors',
    'workshops.feature1Description': 'Learn from industry professionals with years of experience',
    'workshops.feature2Title': 'Small Groups',
    'workshops.feature2Description': 'Intimate class sizes ensure personalized attention',
    'workshops.feature3Title': 'Professional Setting',
    'workshops.feature3Description': 'Train in our fully equipped studio spaces',
    'workshops.feature4Title': 'Comprehensive Materials',
    'workshops.feature4Description': 'All workshop materials and resources included',
    
    // About Page
    'about.founded': 'Founded in 2016',
    'about.heroTitle': 'Who We Are',
    'about.heroSubtitle': 'A vibrant, independent theatre production company dedicated to bringing Turkish culture and arts to UK audiences through exceptional performances and cultural collaborations.',
    'about.historyTitle': 'About Us',
    'about.historyP1': 'Pan Productions is an independent arts production company based in London, founded by theatre producer Zeynep Dalkiran. With her experience in the theatre industry since 1998, she launched Pan Productions to connect Turkish-speaking artists and stories with international audiences.',
    'about.historyP2': 'Theatre being its core, Pan Productions produces both Turkish and English plays, staging original works and adaptations for local and international audiences. Its first production in English, The Importance of Being Earnest (played by immigrants), received praise from critics, marking a bold step in its multilingual vision.',
    'about.historyP3': 'Knowing that art goes far beyond the stage, Pan Productions also produces multidisciplinary art such as music, exhibitions, cultural events and workshops. It also provides publicity, media and communication services to external projects, and offer executive producing support to theatre companies and manage promotion campaigns with care and creativity.',
    'about.historyP4': 'Alongside this, Pan Productions regularly develops and hosts acting and theatre workshops within Pan Academy.',
    'about.visionTitle': 'Our Vision',
    'about.visionP1': '• To be the leading producer of Turkish-speaking cultural events in London.',
    'about.visionP2': '• To engage with theatre as a space for transformation by embracing a collaborative and inclusive approach in conjoining artists, creatives and audiences from diverse cultural backgrounds within the creative process.',
    'about.visionP3': '• To create space for new artistic forms through a spirit of curiosity, innovation and collaboration as a supporter of bold, high-quality, contemporary work.',
    'about.missionTitle': 'Our Mission',
    'about.missionP1': '• To bring Turkish-speaking artists, their stories and cultural richness to London\'s multilingual and multicultural arts scene.',
    'about.missionP2': '• To prioritise originality, quality and collaboration across every stage of the creative process whilst producing first and foremost theatre, but also concerts, exhibitions, sight specific projects and workshops that connect with the audience.',
    'about.missionP3': '• To support various arts organisations with consulting, creative production and communications, building a more inclusive and sustainable artistic environment.',
    'about.valuesTitle': 'Our Values',
    'about.valuesSubtitle': 'The principles that guide everything we do',
    'about.value1Title': 'Cultural Excellence',
    'about.value1Description': 'Bringing the richness of Turkish art and culture to London audiences through world-class productions.',
    'about.value2Title': 'Inclusive Collaboration',
    'about.value2Description': 'Uniting people from all backgrounds and fostering collaboration through the performing arts.',
    'about.value3Title': 'International Bridge',
    'about.value3Description': 'Building cultural bridges between Turkey and the UK through exceptional theatre.',
    'about.value4Title': 'Original Works',
    'about.value4Description': 'Creating and premiering original productions that celebrate Turkish-speaking communities.',
    'about.testimonialsTitle': 'Testimonials',
    'about.testimonialsSubtitle': 'Reviews and feedback from our audiences and workshop participants',
    'about.testimonial1': '...after so many \'traditional\' versions of the play, a fresh take is more than welcome.',
    'about.testimonial1Source': '— Theatre Things',
    'about.testimonial2': 'It was brilliant! I found everything I was looking for.',
    'about.testimonial2Source': '— Devised Theatre Workshop Participant',
    'about.testimonial3': '...breathed new life into it and made it feel like it was written yesterday. So creative and intelligent.',
    'about.testimonial3Source': '— The Importance of Being Earnest Audience Feedback',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We would love to hear from you. Send us a message and we will respond as soon as possible.',
    'contact.firstName': 'First Name',
    'contact.firstNamePlaceholder': 'Enter your first name',
    'contact.lastName': 'Last Name',
    'contact.lastNamePlaceholder': 'Enter your last name',
    'contact.email': 'Email Address',
    'contact.emailPlaceholder': 'Enter your email address',
    'contact.phone': 'Phone Number (Optional)',
    'contact.phonePlaceholder': 'Enter your phone number',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'What is this regarding?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sending': 'Sending...',
    'contact.sendMessage': 'Send Message',
    'contact.messageSent': 'Message Sent! 🎉',
    'contact.messageSuccess': 'Thank you {name}! Your message has been sent. We will get back to you as soon as possible.',
    'contact.error': 'Error',
    'contact.errorMessage': 'Sorry, there was an error sending your message. Please try again or email us directly at panproductionsuk@gmail.com',
    'contact.faqTitle': 'Frequently Asked Questions',
    'contact.faqSubtitle': 'Quick answers to common questions',
    'contact.faq1Question': 'How can I audition for Pan Productions shows?',
    'contact.faq1Answer': 'Audition information is posted on our Productions page and social media. We typically hold open auditions 6-8 weeks before each production begins rehearsals.',
    'contact.faq2Question': 'How can I stay updated about upcoming shows and workshops?',
    'contact.faq2Answer': 'Subscribe to our newsletter, follow us on social media, and check our website regularly for the latest show announcements and ticket information.',
    'contact.faq3Question': 'What are the prerequisites for your workshops?',
    'contact.faq3Answer': 'Our only requirement is enthusiasm and an interest in theatre. No previous training is necessary.',
    'contact.faq4Question': 'Can I stage an original play I\'ve written?',
    'contact.faq4Answer': 'Absolutely! Reach out to us at hello@panproductions.co.uk and our team will be in touch to discuss matters further.',
    
    // Marketing Page
    'marketing.heroTitle': 'PR & Marketing Excellence',
    'marketing.heroSubtitle': 'Amplify Your Creative Vision',
    'marketing.heroDescription': 'Pan Productions provides bespoke PR & Marketing strategies and support on a project-by-project basis in theatre, music, and exhibitions.',
    'marketing.getInTouch': 'Get In Touch',
    'marketing.description': 'Pan Productions provides bespoke PR & Marketing strategies and support on a project-by-project basis in theatre, music, and exhibitions.',
    'marketing.service1Title': 'Strategic Marketing',
    'marketing.service1Description': 'Comprehensive marketing strategies tailored to your production unique needs and target audience.',
    'marketing.service1Feature1': 'Market Research',
    'marketing.service1Feature2': 'Audience Analysis',
    'marketing.service1Feature3': 'Brand Positioning',
    'marketing.service1Feature4': 'Campaign Planning',
    'marketing.service2Title': 'Public Relations',
    'marketing.service2Description': 'Professional PR services to maximize your production visibility and media coverage.',
    'marketing.service2Feature1': 'Press Releases',
    'marketing.service2Feature2': 'Media Relations',
    'marketing.service2Feature3': 'Interview Coordination',
    'marketing.service2Feature4': 'Crisis Management',
    'marketing.service3Title': 'Content Creation',
    'marketing.service3Description': 'High-quality promotional content including photography, videography, and graphic design.',
    'marketing.service3Feature1': 'Professional Photography',
    'marketing.service3Feature2': 'Video Production',
    'marketing.service3Feature3': 'Graphic Design',
    'marketing.service3Feature4': 'Social Media Content',
    'marketing.service4Title': 'Digital Marketing',
    'marketing.service4Description': 'Complete digital marketing solutions to reach audiences across all online platforms.',
    'marketing.service4Feature1': 'Social Media Marketing',
    'marketing.service4Feature2': 'Website Development',
    'marketing.service4Feature3': 'SEO Optimization',
    'marketing.service4Feature4': 'Email Campaigns',
    'marketing.ctaTitle': 'Ready to Promote Your Production?',
    
    // Productions Page
    'productions.title': 'Productions',
    'productions.subtitle': 'Discover our past, current, and upcoming theatre productions',
    'productions.tabCurrent': 'Current',
    'productions.tabUpcoming': 'Upcoming',
    'productions.tabPast': 'Past',
    'productions.by': 'by',
    'productions.buyTickets': 'Buy Tickets',
    'productions.comingSoon': 'Coming Soon',
    'productions.archive': 'Archive',
    'productions.statusCurrent': 'Now Playing',
    'productions.statusUpcoming': 'Coming Soon',
    'productions.statusPast': 'Past',
    'productions.noCurrent': 'No current productions at the moment. Check back soon for updates!',
    'productions.noUpcoming': 'No upcoming productions announced yet. Stay tuned for exciting news!',
    'productions.noPast': 'No past productions to display.',
    'productions.ctaTitle': 'Want to Get Involved?',
    'productions.ctaDescription': 'Join our team for upcoming productions. We are always looking for talented performers, crew members, and volunteers.',
    'productions.contactUs': 'Contact Us',
    
    // Get Involved Page
    'getInvolved.badge': 'Join Our Community',
    'getInvolved.title1': 'Get',
    'getInvolved.title2': 'Involved',
    'getInvolved.heroDescription': 'Contribute to Pan Productions mission in various ways',
    'getInvolved.heroCta': 'Start Your Journey',
    'getInvolved.waysTitle': 'Ways to Get Involved',
    'getInvolved.waysSubtitle': 'Choose how you would like to support our mission',
    'getInvolved.requiredSkills': 'Required Skills',
    'getInvolved.mostPopular': 'Most Popular',
    'getInvolved.ctaPrimary': 'Get Started Today',
    'getInvolved.ctaSecondary': 'Learn More',
    'getInvolved.partnershipLevelsTitle': 'Partnership Levels',
    'getInvolved.partnershipLevelsSubtitle': 'Flexible partnership options for every budget',
    'getInvolved.impact1Label': 'Students Reached',
    'getInvolved.impact2Label': 'Productions Funded',
    'getInvolved.impact3Label': 'Volunteer Hours',
    'getInvolved.impact4Label': 'Scholarships Provided',
    'getInvolved.title': 'Get Involved',
    'getInvolved.subtitle': 'Contribute to Pan Productions mission in various ways',
    'getInvolved.donateTitle': 'Donate',
    'getInvolved.donateSubtitle': 'Support Our Mission',
    'getInvolved.donateDescription': 'Help us continue creating powerful theatre experiences and providing arts education to our community.',
    'getInvolved.donateFeature1': 'Support new productions',
    'getInvolved.donateFeature2': 'Fund educational programs',
    'getInvolved.donateFeature3': 'Provide scholarships',
    'getInvolved.donateFeature4': 'Maintain our facilities',
    'getInvolved.donateCta': 'Make a Donation',
    'getInvolved.volunteerTitle': 'Volunteer',
    'getInvolved.volunteerSubtitle': 'Join Our Team',
    'getInvolved.volunteerDescription': 'Be part of our creative community and gain hands-on experience in professional theatre production.',
    'getInvolved.volunteerFeature1': 'Production assistance',
    'getInvolved.volunteerFeature2': 'Event management',
    'getInvolved.volunteerFeature3': 'Marketing support',
    'getInvolved.volunteerFeature4': 'Administrative help',
    'getInvolved.volunteerCta': 'Apply to Volunteer',
    'getInvolved.partnerTitle': 'Partner',
    'getInvolved.partnerSubtitle': 'Corporate Collaboration',
    'getInvolved.partnerDescription': 'Partner with us to create meaningful connections between your business and the arts community.',
    'getInvolved.partnerFeature1': 'Brand visibility',
    'getInvolved.partnerFeature2': 'Community engagement',
    'getInvolved.partnerFeature3': 'Employee benefits',
    'getInvolved.partnerFeature4': 'Networking opportunities',
    'getInvolved.partnerCta': 'Become a Partner',
    'getInvolved.volunteerRolesTitle': 'Volunteer Roles',
    'getInvolved.volunteerRolesSubtitle': 'Discover the various ways you can join us',
    'getInvolved.role1Title': 'Production Assistant',
    'getInvolved.role1Commitment': '10-15 hours/week',
    'getInvolved.role1Description': 'Help our production team with backstage operations, set construction, and technical support.',
    'getInvolved.role1Skill1': 'Reliability',
    'getInvolved.role1Skill2': 'Physical ability',
    'getInvolved.role1Skill3': 'Team player',
    'getInvolved.role2Title': 'Marketing Volunteer',
    'getInvolved.role2Commitment': '5-8 hours/week',
    'getInvolved.role2Description': 'Help promote our productions through social media, content creation, and community outreach.',
    'getInvolved.role2Skill1': 'Social media',
    'getInvolved.role2Skill2': 'Writing',
    'getInvolved.role2Skill3': 'Photography',
    'getInvolved.role3Title': 'Event Coordinator',
    'getInvolved.role3Commitment': '8-12 hours/week',
    'getInvolved.role3Description': 'Assist in organizing special events, workshops, and community engagement activities.',
    'getInvolved.role3Skill1': 'Organization',
    'getInvolved.role3Skill2': 'Communication',
    'getInvolved.role3Skill3': 'Event planning',
    'getInvolved.role4Title': 'Education Support',
    'getInvolved.role4Commitment': '6-10 hours/week',
    'getInvolved.role4Description': 'Support Pan Academy workshops and educational programs for students of all ages.',
    'getInvolved.role4Skill1': 'Patience',
    'getInvolved.role4Skill2': 'Teaching interest',
    'getInvolved.role4Skill3': 'Arts background',
    'getInvolved.partnershipBenefitsTitle': 'Partnership Levels',
    'getInvolved.partnershipBenefitsSubtitle': 'Flexible partnership options for every budget',
    'getInvolved.partner1Level': 'Supporting Partner',
    'getInvolved.partner1Amount': '£1,000 - £2,500',
    'getInvolved.partner1Benefit1': 'Logo in programs',
    'getInvolved.partner1Benefit2': 'Social media mentions',
    'getInvolved.partner1Benefit3': '2 complimentary tickets per show',
    'getInvolved.partner2Level': 'Principal Partner',
    'getInvolved.partner2Amount': '£2,500 - £5,000',
    'getInvolved.partner2Benefit1': 'Logo on all marketing materials',
    'getInvolved.partner2Benefit2': 'VIP premiere invitations',
    'getInvolved.partner2Benefit3': '4 complimentary tickets per show',
    'getInvolved.partner2Benefit4': 'Exclusive networking events',
    'getInvolved.partner3Level': 'Leading Partner',
    'getInvolved.partner3Amount': '£5,000+',
    'getInvolved.partner3Benefit1': 'Exclusive production sponsorship',
    'getInvolved.partner3Benefit2': 'Private events and meet-and-greets',
    'getInvolved.partner3Benefit3': 'Unlimited tickets for the season',
    'getInvolved.partner3Benefit4': 'Recognition in all communications',
    'getInvolved.impactTitle': 'Our Impact',
    'getInvolved.impactSubtitle': 'Your support makes a real difference',
    'getInvolved.impact1Title': 'Students Reached',
    'getInvolved.impact1Description': 'Through our free workshop programs',
    'getInvolved.impact2Title': 'Productions Funded',
    'getInvolved.impact2Description': 'With donations last year',
    'getInvolved.impact3Title': 'Volunteer Hours',
    'getInvolved.impact3Description': 'Contributed by community members',
    'getInvolved.impact4Title': 'Scholarships Provided',
    'getInvolved.impact4Description': 'To passionate students',
    'getInvolved.ctaTitle': 'Ready to Join Us?',
    'getInvolved.ctaDescription': 'However you choose to get involved, every contribution matters. Get in touch with us today.',
    'getInvolved.commitment': 'Commitment',
    'getInvolved.skills': 'Skills',
    'getInvolved.benefits': 'Benefits',
    
    // News Page
    'news.title1': 'Latest',
    'news.title2': 'News & Press',
    'news.subtitle': 'Stay updated with our latest announcements, reviews, and press coverage',
    
    // Footer
    'footer.tagline': 'Bringing stories to life through exceptional theatre',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
  },
  TR: {
    // Navigation
    'nav.home': 'Home',
    'nav.productions': 'Productions',
    'nav.marketing': 'PR & Marketing',
    'nav.academy': 'Pan Academy',
    'nav.workshops': 'Workshops',
    'nav.lessons': 'Lessons',
    'nav.about': 'About Us',
    'nav.news': 'News & Press',
    'nav.contact': 'Contact Us',
    'nav.getInvolved': 'Get Involved',
    
    // About Page
    'about.founded': '2016 Yılında Kuruldu',
    'about.heroTitle': 'Biz Kimiz?',
    'about.heroSubtitle': 'Türk kültürünü ve sanatını İngiltere izleyicilerine olağanüstü performanslar ve kültürel işbirlikleri yoluyla taşımaya adanmış, canlı ve bağımsız bir tiyatro prodüksiyon şirketi.',
    'about.historyTitle': 'Tarihçe',
    'about.historyP1': 'Pan Productions (PP), Londra merkezli, canlı ve bağımsız bir tiyatro prodüksiyon şirketidir. Şirket, uluslararası çapta tanınmış Türk oyuncular, sanatçılar ve müzisyenleri içeren Türkçe prodüksiyonları İngiltere izleyicilerine sunmaya kendini adamıştır.',
    'about.historyP2': 'Kasım 2016\'da tiyatro yapımcısı Zeynep Dalkıran tarafından kurulan PP, Türkçe tiyatroda on yılı aşkın deneyimden doğdu. Zeynep, ticari ve ticari olmayan prodüksiyonlardaki -tiyatro, sanat sergileri ve konserler- kapsamlı geçmişini birleştirerek Türk kültürünü Londra sahnesinde kutlayan ve yükselten bir şirket yarattı.',
    'about.historyP3': 'Pan Productions, ulusal ve uluslararası düzeyde olağanüstü performanslar üretmeyi ve ortak üretmeyi amaçlarken, diğer tiyatro şirketlerine de en kaliteli prodüksiyon hizmetleri sunmaktadır. Yerel organizatörler ve küresel ortaklarla işbirliği yaparak, PP kültürel köprüler kurmaya ve Türk sanatı, müziği ve tiyatrosunun zenginliğini çeşitli izleyicilere taşımaya devam ediyor.',
    'about.missionTitle': 'Misyonumuz',
    'about.missionP1': 'Pan Productions\'ın misyonu, Londra\'da önde gelen Türkçe kültürel etkinlikler üretmek, konserleri, oyunları ve sergileri aracılığıyla en iyi oyuncuları, sanatçıları ve müzisyenleri bir araya getirmektir. Türk sanatının zenginliğini sergileyen ve İngiltere\'deki çeşitli izleyicilerle bağlantı kuran dünya standartlarında prodüksiyonlar yaratmaya adanmışız.',
    'about.missionP2': 'Ana prodüksiyonlarımıza ek olarak, Pan Productions bir dizi tamamlayıcı etkinlik sunmaktadır - samimi oturum sezonları, tiyatro turları, mekana özel performanslar ve tek gecelik özel etkinlikler dahil. Ayrıca araştırma, danışmanlık ve lojistik planlama hizmetleri sağlayarak, kültürel ve sanatsal projeleri gelişimin tüm aşamalarında destekliyoruz.',
    'about.visionTitle': 'Vizyonumuz',
    'about.visionP1': 'Vizyonumuz, yalnızca yerleşik Türkçe prodüksiyonları (Türkiye\'de kanıtlanmış ve kutlanmış) desteklemek ve finanse etmek değil, aynı zamanda orijinal eserler geliştirmek ve bunları Londra\'daki Türkçe konuşan topluluk için prömiyerini yapmaktır.',
    'about.visionP2': 'Bugün, ana odak noktamız tiyatro dünyasında yatıyor - sahnede yaratılabilecek drama ve performansın tüm yelpazesini kucaklayarak. Londra merkezli bir prodüksiyon şirketi olarak, Pan Productions her geçmişten insanları bir araya getirmeyi, gösteri sanatları aracılığıyla işbirliği, kapsayıcılık ve kültürel alışverişi teşvik etmeyi amaçlamaktadır.',
    'about.valuesTitle': 'Değerlerimiz',
    'about.valuesSubtitle': 'Yaptığımız her şeye rehberlik eden ilkeler',
    'about.value1Title': 'Kültürel Mükemmellik',
    'about.value1Description': 'Dünya standartlarında prodüksiyonlar aracılığıyla Türk sanatı ve kültürünün zenginliğini Londra izleyicilerine sunmak.',
    'about.value2Title': 'Kapsayıcı İşbirliği',
    'about.value2Description': 'Gösteri sanatları aracılığıyla her geçmişten insanları bir araya getirmek ve işbirliğini teşvik etmek.',
    'about.value3Title': 'Uluslararası Köprü',
    'about.value3Description': 'Olağanüstü tiyatro gösterileri aracılığıyla Türkiye ve İngiltere arasında kültürel köprüler kurmak.',
    'about.value4Title': 'Orijinal Eserler',
    'about.value4Description': 'Türkçe konuşan toplulukları kutlayan orijinal prodüksiyonlar yaratmak ve prömiyerini yapmak.',
    'about.testimonialsTitle': 'Görüşler',
    'about.testimonialsSubtitle': 'İzleyicilerimizden ve atölye katılımcılarından değerlendirmeler ve yorumlar',
    'about.testimonial1': '...pek çok \'geleneksel\' oyun versiyonundan sonra, taze bir bakış açısı fazlasıyla hoş karşılanıyor.',
    'about.testimonial1Source': '— Theatre Things',
    'about.testimonial2': 'Harikaydı! Aradığım her şeyi buldum.',
    'about.testimonial2Source': '— Devised Theatre Atölyesi Katılımcısı',
    'about.testimonial3': '...onu yeniden canlandırdı ve sanki dün yazılmış gibi hissettirdi. Çok yaratıcı ve zeki.',
    'about.testimonial3Source': '— The Importance of Being Earnest İzleyici Yorumu',
    
    // Contact Page
    'contact.title': 'İletişim',
    'contact.subtitle': 'Sizden haber almak isteriz. Bize mesaj gönderin, en kısa sürede yanıt verelim.',
    'contact.firstName': 'Ad',
    'contact.firstNamePlaceholder': 'Adınızı girin',
    'contact.lastName': 'Soyad',
    'contact.lastNamePlaceholder': 'Soyadınızı girin',
    'contact.email': 'E-posta Adresi',
    'contact.emailPlaceholder': 'E-posta adresinizi girin',
    'contact.phone': 'Telefon Numarası (İsteğe Bağlı)',
    'contact.phonePlaceholder': 'Telefon numaranızı girin',
    'contact.subject': 'Konu',
    'contact.subjectPlaceholder': 'Bu nedir?',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Size nasıl yardımcı olabileceğimizi anlatın...',
    'contact.sending': 'Gönderiliyor...',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.messageSent': 'Mesaj Gönderildi! 🎉',
    'contact.messageSuccess': 'Teşekkürler {name}! Mesajınız gönderildi. En kısa sürede size geri döneceğiz.',
    'contact.error': 'Hata',
    'contact.errorMessage': 'Üzgünüz, mesajınızı gönderirken bir hata oluştu. Lütfen tekrar deneyin veya doğrudan panproductionsuk@gmail.com adresine e-posta gönderin',
    'contact.faqTitle': 'Sıkça Sorulan Sorular',
    'contact.faqSubtitle': 'Sık sorulan sorulara hızlı yanıtlar',
    'contact.faq1Question': 'Pan Productions gösterilerine nasıl seçme yapabilirim?',
    'contact.faq1Answer': 'Seçme bilgileri Prodüksiyonlar sayfamızda ve sosyal medyada yayınlanır. Genellikle her prodüksiyon provalarına başlamadan 6-8 hafta önce açık seçmeler düzenliyoruz.',
    'contact.faq2Question': 'Yaklaşan gösteriler ve atölyeler hakkında nasıl güncel kalabilirim?',
    'contact.faq2Answer': 'Bültenimize abone olun, bizi sosyal medyada takip edin ve en son gösteri duyuruları ve bilet bilgileri için web sitemizi düzenli olarak kontrol edin.',
    'contact.faq3Question': 'Atölyeleriniz için giriş gereksinimleri nelerdir?',
    'contact.faq3Answer': 'Tek gereksimimiz coşku ve tiyatroya ilgidir. Önceki eğitim gerekli değildir.',
    'contact.faq4Question': 'Yazdığım orijinal bir eseri sahneleyebilir miyim?',
    'contact.faq4Answer': 'Kesinlikle! hello@panproductions.co.uk adresinden bize ulaşın ve ekibimiz konuları daha fazla görüşmek için sizinle iletişime geçecektir.',
    
    // Marketing Page
    'marketing.heroTitle': 'PR & Pazarlama Mükemmelliği',
    'marketing.heroSubtitle': 'Yaratıcı Vizyonunuzu Güçlendirin',
    'marketing.heroDescription': 'Pan Productions, tiyatro, müzik ve sergilerde proje bazında özel PR & Pazarlama stratejileri ve destek sağlar.',
    'marketing.getInTouch': 'İletişime Geçin',
    'marketing.description': 'Pan Productions, tiyatro, müzik ve sergilerde proje bazında özel PR & Pazarlama stratejileri ve destek sağlar.',
    'marketing.service1Title': 'Stratejik Pazarlama',
    'marketing.service1Description': 'Prodüksiyonunuzun benzersiz ihtiyaçlarına ve hedef kitlesine özel kapsamlı pazarlama stratejileri.',
    'marketing.service1Feature1': 'Pazar Araştırması',
    'marketing.service1Feature2': 'İzleyici Analizi',
    'marketing.service1Feature3': 'Marka Konumlandırma',
    'marketing.service1Feature4': 'Kampanya Planlama',
    'marketing.service2Title': 'Halkla İlişkiler',
    'marketing.service2Description': 'Prodüksiyonunuzun görünürlüğünü ve medya kapsamını en üst düzeye çıkarmak için profesyonel PR hizmetleri.',
    'marketing.service2Feature1': 'Basın Bültenleri',
    'marketing.service2Feature2': 'Medya İlişkileri',
    'marketing.service2Feature3': 'Röportaj Koordinasyonu',
    'marketing.service2Feature4': 'Kriz Yönetimi',
    'marketing.service3Title': 'İçerik Oluşturma',
    'marketing.service3Description': 'Fotoğrafçılık, videografi ve grafik tasarım dahil yüksek kaliteli tanıtım içeriği.',
    'marketing.service3Feature1': 'Profesyonel Fotoğrafçılık',
    'marketing.service3Feature2': 'Video Prodüksiyonu',
    'marketing.service3Feature3': 'Grafik Tasarım',
    'marketing.service3Feature4': 'Sosyal Medya İçeriği',
    'marketing.service4Title': 'Dijital Pazarlama',
    'marketing.service4Description': 'Tüm çevrimiçi platformlarda izleyicilere ulaşmak için eksiksiz dijital pazarlama çözümleri.',
    'marketing.service4Feature1': 'Sosyal Medya Pazarlaması',
    'marketing.service4Feature2': 'Web Sitesi Geliştirme',
    'marketing.service4Feature3': 'SEO Optimizasyonu',
    'marketing.service4Feature4': 'E-posta Kampanyaları',
    'marketing.ctaTitle': 'Prodüksiyonunuzu Tanıtmaya Hazır Mısınız?',
    
    // Productions Page
    'productions.title': 'Prodüksiyonlar',
    'productions.subtitle': 'Geçmiş, güncel ve gelecek tiyatro prodüksiyonlarımızı keşfedin',
    'productions.tabCurrent': 'Güncel',
    'productions.tabUpcoming': 'Yaklaşan',
    'productions.tabPast': 'Geçmiş',
    'productions.by': 'yazan',
    'productions.buyTickets': 'Bilet Satın Al',
    'productions.comingSoon': 'Çok Yakında',
    'productions.archive': 'Arşiv',
    'productions.statusCurrent': 'Şimdi Sahnede',
    'productions.statusUpcoming': 'Yakında',
    'productions.statusPast': 'Geçmiş',
    'productions.noCurrent': 'Şu anda güncel prodüksiyon bulunmamaktadır. Güncellemeler için yakında tekrar kontrol edin!',
    'productions.noUpcoming': 'Henüz yaklaşan prodüksiyon duyurulmadı. Heyecan verici haberler için bizi takipte kalın!',
    'productions.noPast': 'Görüntülenecek geçmiş prodüksiyon yok.',
    'productions.ctaTitle': 'Bize Katılmak İster misiniz?',
    'productions.ctaDescription': 'Yaklaşan prodüksiyonlar için ekibimize katılın. Her zaman yetenekli oyuncular, ekip üyeleri ve gönüllüler arıyoruz.',
    'productions.contactUs': 'Bize Ulaşın',
    
    // Workshops Page
    'workshops.title': 'Atölyeler',
    'workshops.subtitle': 'Her yaştan ve seviyeden katılımcı için kapsamlı tiyatro atölyeleri',
    'workshops.badgeTitle': 'Pan Academy Atölyeleri',
    'workshops.heroTitle1': 'Performans Becerilerinizi',
    'workshops.heroTitle2': 'Geliştirin',
    'workshops.heroParagraph1': 'Pan Academy, Kuzey Londra\'nın önde gelen oyunculuk okuludur. Her deneyim seviyesine uygun çeşitli oyunculuk sınıfları ve kursları sunuyoruz. Kendinize meydan okumak, yeni beceriler geliştirmek veya oyunculuk yolculuğunuzda bir sonraki adımı atmak istiyorsanız, sizin için bir kursumuz var. Akşam, hafta sonu ve part-time programlarımız yoğun programınıza uyacak şekilde yapılandırılmıştır.',
    'workshops.heroParagraph2': 'Oyunculukta yeniyseniz, Başlangıç Kurslarımız İleri ve İleri Düzey seviyelere geçmeden önce başlamanıza yardımcı olacak eğlenceli ve destekleyici bir ortam sağlar. Profesyonel bir kariyere heves edenler için Endüstri Kurslarımız, oyunculuk endüstrisinin taleplerine hazırlanmanız için uzman eğitim sunar. Çeşitli teknikleri kapsayan yoğun bir deneyim arıyorsanız, Oyunculuk Temelleri kursumuz mükemmel bir seçimdir.',
    'workshops.heroParagraph3': 'Yetişkinler için çeşitli oyunculuk kursları sunuyoruz; Oyunculuk Sınıfları, Ses ve Hareket Eğitimi ile birlikte oyun yazarlığı ve Meisner, Stanislavski ve Method Oyunculuk gibi özelleşmiş oyunculuk yöntemleri gibi özel atölyeler.',
    'workshops.contactUs': 'Bize Ulaşın',
    'workshops.tabTheater': 'Tiyatro',
    'workshops.tabMusic': 'Müzik',
    'workshops.tabArt': 'Sanat',
    'workshops.tabFilm': 'Film',
    'workshops.level': 'Seviye',
    'workshops.duration': 'Süre',
    'workshops.schedule': 'Program',
    'workshops.instructor': 'Eğitmen',
    'workshops.price': 'Fiyat',
    'workshops.enrollNow': 'Şimdi Kaydol',
    'workshops.learnMore': 'Daha Fazla Bilgi',
    'workshops.noWorkshops': 'Şu anda bu kategoride atölye bulunmamaktadır. Yeni atölyeler için yakında tekrar kontrol edin!',
    'workshops.pastWorkshopsTitle': 'Geçmiş Atölyeler',
    'workshops.pastWorkshopsSubtitle': 'Performans becerilerini geliştirmeye yardımcı olan daha önce düzenlenen atölyelerimizi keşfedin',
    'workshops.completed': 'Atölye Tamamlandı',
    'workshops.noMusic': 'Şu anda müzik atölyeleri bulunmamaktadır.',
    'workshops.noArt': 'Şu anda sanat atölyeleri bulunmamaktadır.',
    'workshops.noFilm': 'Şu anda film atölyeleri bulunmamaktadır.',
    'workshops.ctaTitle': 'Aradığınızı Bulamadınız mı?',
    'workshops.ctaDescription': 'Özelleştirilmiş atölyeler ve özel koçluk seansları sunuyoruz. Özel eğitim ihtiyaçlarınızı tartışmak için bizimle iletişime geçin.',
    'workshops.requestLesson': 'Özel Ders Talep Et',
    'workshops.feature1Title': 'Uzman Eğitmenler',
    'workshops.feature1Description': 'Yıllarca deneyime sahip sektör profesyonellerinden öğrenin',
    'workshops.feature2Title': 'Küçük Gruplar',
    'workshops.feature2Description': 'Samimi sınıf boyutları kişiselleştirilmiş ilgi sağlar',
    'workshops.feature3Title': 'Profesyonel Ortam',
    'workshops.feature3Description': 'Tam donanımlı stüdyo alanlarımızda eğitim alın',
    'workshops.feature4Title': 'Kapsamlı Materyaller',
    'workshops.feature4Description': 'Tüm atölye materyalleri ve kaynakları dahildir',
    
    // Get Involved Page
    'getInvolved.badge': 'Topluluğumuza Katılın',
    'getInvolved.title1': 'Bize',
    'getInvolved.title2': 'Katılın',
    'getInvolved.heroDescription': 'Pan Productions\'ın misyonuna çeşitli yollarla katkıda bulunun',
    'getInvolved.heroCta': 'Yolculuğunuza Başlayın',
    'getInvolved.waysTitle': 'Katılım Yolları',
    'getInvolved.waysSubtitle': 'Misyonumuzu nasıl desteklemek istediğinizi seçin',
    'getInvolved.requiredSkills': 'Gerekli Beceriler',
    'getInvolved.mostPopular': 'En Popüler',
    'getInvolved.ctaPrimary': 'Bugün Başlayın',
    'getInvolved.ctaSecondary': 'Daha Fazla Bilgi',
    'getInvolved.partnershipLevelsTitle': 'Ortaklık Seviyeleri',
    'getInvolved.partnershipLevelsSubtitle': 'Her bütçeye uygun esnek ortaklık seçenekleri',
    'getInvolved.impact1Label': 'Ulaşılan Öğrenci',
    'getInvolved.impact2Label': 'Finanse Edilen Prodüksiyon',
    'getInvolved.impact3Label': 'Gönüllü Saati',
    'getInvolved.impact4Label': 'Sağlanan Burs',
    'getInvolved.title': 'Bize Katılın',
    'getInvolved.subtitle': 'Farklı yollarla Pan Productions\'ın misyonuna katkıda bulunun',
    'getInvolved.donateTitle': 'Bağış Yapın',
    'getInvolved.donateSubtitle': 'Misyonumuzu Destekleyin',
    'getInvolved.donateDescription': 'Güçlü tiyatro deneyimleri yaratmaya ve topluluğumuza sanat eğitimi sağlamaya devam etmemize yardımcı olun.',
    'getInvolved.donateFeature1': 'Yeni prodüksiyonları destekleyin',
    'getInvolved.donateFeature2': 'Eğitim programlarını fonlayın',
    'getInvolved.donateFeature3': 'Burs sağlayın',
    'getInvolved.donateFeature4': 'Tesislerimizi sürdürün',
    'getInvolved.donateCta': 'Bağış Yapın',
    'getInvolved.volunteerTitle': 'Gönüllü Olun',
    'getInvolved.volunteerSubtitle': 'Ekibimize Katılın',
    'getInvolved.volunteerDescription': 'Yaratıcı topluluğumuzun bir parçası olun ve profesyonel tiyatro prodüksiyonunda uygulamalı deneyim kazanın.',
    'getInvolved.volunteerFeature1': 'Prodüksiyon yardımı',
    'getInvolved.volunteerFeature2': 'Etkinlik yönetimi',
    'getInvolved.volunteerFeature3': 'Pazarlama desteği',
    'getInvolved.volunteerFeature4': 'İdari yardım',
    'getInvolved.volunteerCta': 'Gönüllü Başvurusu',
    'getInvolved.partnerTitle': 'Ortak Olun',
    'getInvolved.partnerSubtitle': 'Kurumsal İşbirliği',
    'getInvolved.partnerDescription': 'İşiniz ile sanat topluluğu arasında anlamlı bağlantılar oluşturmak için bizimle ortak olun.',
    'getInvolved.partnerFeature1': 'Marka görünürlüğü',
    'getInvolved.partnerFeature2': 'Topluluk katılımı',
    'getInvolved.partnerFeature3': 'Çalışan avantajları',
    'getInvolved.partnerFeature4': 'Ağ oluşturma fırsatları',
    'getInvolved.partnerCta': 'Ortaklık Talebi',
    'getInvolved.volunteerRolesTitle': 'Gönüllü Rolleri',
    'getInvolved.volunteerRolesSubtitle': 'Aramıza katılmanın çeşitli yollarını keşfedin',
    'getInvolved.role1Title': 'Prodüksiyon Asistanı',
    'getInvolved.role1Commitment': 'Haftada 10-15 saat',
    'getInvolved.role1Description': 'Prodüksiyon ekibimize sahne arkası operasyonları, set inşaatı ve teknik destek konularında yardımcı olun.',
    'getInvolved.role1Skill1': 'Güvenilirlik',
    'getInvolved.role1Skill2': 'Fiziksel yetenek',
    'getInvolved.role1Skill3': 'Takım oyuncusu',
    'getInvolved.role2Title': 'Pazarlama Gönüllüsü',
    'getInvolved.role2Commitment': 'Haftada 5-8 saat',
    'getInvolved.role2Description': 'Sosyal medya, içerik oluşturma ve topluluk erişimi yoluyla prodüksiyonlarımızı tanıtmaya yardımcı olun.',
    'getInvolved.role2Skill1': 'Sosyal medya',
    'getInvolved.role2Skill2': 'Yazma',
    'getInvolved.role2Skill3': 'Fotoğrafçılık',
    'getInvolved.role3Title': 'Etkinlik Koordinatörü',
    'getInvolved.role3Commitment': 'Haftada 8-12 saat',
    'getInvolved.role3Description': 'Özel etkinlikler, atölyeler ve topluluk katılım faaliyetlerinin organizasyonunda yardımcı olun.',
    'getInvolved.role3Skill1': 'Organizasyon',
    'getInvolved.role3Skill2': 'İletişim',
    'getInvolved.role3Skill3': 'Etkinlik planlama',
    'getInvolved.role4Title': 'Eğitim Desteği',
    'getInvolved.role4Commitment': 'Haftada 6-10 saat',
    'getInvolved.role4Description': 'Her yaştan öğrenci için Pan Akademi atölyeleri ve eğitim programlarına destek olun.',
    'getInvolved.role4Skill1': 'Sabır',
    'getInvolved.role4Skill2': 'Öğretme ilgisi',
    'getInvolved.role4Skill3': 'Sanat altyapısı',
    'getInvolved.partnershipBenefitsTitle': 'Ortaklık Seviyeleri',
    'getInvolved.partnershipBenefitsSubtitle': 'Her bütçeye uygun esnek ortaklık seçenekleri',
    'getInvolved.partnerLevel1': 'Destekleyen Ortak',
    'getInvolved.partnerLevel1Amount': '£1.000 - £2.500',
    'getInvolved.partnerLevel1Benefit1': 'Programlarda logo',
    'getInvolved.partnerLevel1Benefit2': 'Sosyal medya anonsları',
    'getInvolved.partnerLevel1Benefit3': 'Gösteri başına 2 ücretsiz bilet',
    'getInvolved.partnerLevel2': 'Ana Ortak',
    'getInvolved.partnerLevel2Amount': '£2.500 - £5.000',
    'getInvolved.partnerLevel2Benefit1': 'Tüm pazarlama materyallerinde logo',
    'getInvolved.partnerLevel2Benefit2': 'Prömiyere VIP davetler',
    'getInvolved.partnerLevel2Benefit3': 'Gösteri başına 4 ücretsiz bilet',
    'getInvolved.partnerLevel2Benefit4': 'Özel ağ oluşturma etkinlikleri',
    'getInvolved.partnerLevel3': 'Öncü Ortak',
    'getInvolved.partnerLevel3Amount': '£5.000+',
    'getInvolved.partnerLevel3Benefit1': 'Özel prodüksiyon sponsorluğu',
    'getInvolved.partnerLevel3Benefit2': 'Özel etkinlikler ve tanışmalar',
    'getInvolved.partnerLevel3Benefit3': 'Sezon için sınırsız bilet',
    'getInvolved.partnerLevel3Benefit4': 'Tüm iletişimlerde tanınma',
    'getInvolved.impactTitle': 'Etkimiz',
    'getInvolved.impactSubtitle': 'Desteğiniz gerçek fark yaratıyor',
    'getInvolved.impact1Title': 'Öğrencilere Ulaşıldı',
    'getInvolved.impact1Description': 'Ücretsiz atölye programlarımız aracılığıyla',
    'getInvolved.impact2Title': 'Prodüksiyon Finanse Edildi',
    'getInvolved.impact2Description': 'Geçen yıl bağışlarla',
    'getInvolved.impact3Title': 'Gönüllü Saat',
    'getInvolved.impact3Description': 'Topluluk üyelerinden katkı',
    'getInvolved.impact4Title': 'Burs Sağlandı',
    'getInvolved.impact4Description': 'Tutkulu öğrencilere',
    'getInvolved.ctaTitle': 'Aramıza Katılmaya Hazır Mısınız?',
    'getInvolved.ctaDescription': 'İşinizi nasıl dahil etmek isterseniz edin, her katkı önemlidir. Bugün bizimle iletişime geçin.',
    'getInvolved.commitment': 'Sorumluluk',
    'getInvolved.skills': 'Beceriler',
    'getInvolved.benefits': 'Avantajlar',
    
    // Hero Section
    'hero.slide1.title': 'Hikayelere Sahnede Hayat Veriyoruz',
    'hero.slide1.subtitle': 'Prodüksiyonlar & Deneyim',
    'hero.slide1.description': 'Pan Productions ile unutulmaz tiyatro prodüksiyonlarını yaşayın.',
    'hero.slide1.cta': 'Yaklaşan Gösterileri İnceleyin',
    
    'hero.slide2.title': 'Hikayelerimizi Sahnenin Ötesine Taşıyoruz',
    'hero.slide2.subtitle': 'PR & Pazarlama',
    'hero.slide2.description': 'PR ve pazarlama ekibimiz, her prodüksiyonun hak ettiği izleyiciye ulaşmasını sağlar.',
    'hero.slide2.cta': 'PR Hizmetlerimizi Keşfedin',
    
    'hero.slide3.title': 'Pan Akademi ile Yaratıcılığa Güç Veriyoruz',
    'hero.slide3.subtitle': 'Pan Akademi Atölyeleri',
    'hero.slide3.description': 'Atölyelerimiz gelecek nesil sanatçılara ilham verir ve onları geliştirir.',
    'hero.slide3.cta': 'Atölyelere Katılın',
    
    // Index Page
    'index.whatWeOffer': 'Neler Sunuyoruz',
    'index.discover': 'Pan Productions\'ı Keşfedin',
    'index.discoverDescription': 'Profesyonel tiyatro prodüksiyonlarından kapsamlı drama eğitimine kadar, hikayelere hayat veriyoruz ve gelecek nesil sanatçıları yetiştiriyoruz.',
    
    'index.highlights.productions.title': 'Güncel Prodüksiyonlar',
    'index.highlights.productions.description': 'Yetenekli oyuncu kadrosu ve büyüleyici hikayeleriyle dikkat çeken tiyatro gösterilerimizi deneyimleyin.',
    'index.highlights.academy.title': 'Pan Akademi',
    'index.highlights.academy.description': 'Her seviyeden oyuncu için, sektör uzmanları tarafından verilen profesyonel atölyeler ve dersler.',
    'index.highlights.news.title': 'Haberler & Basın',
    'index.highlights.news.description': 'En son haberlerimiz, eleştirilerimiz ve tiyatro dünyasından basın haberlerimizle güncel kalın.',
    'index.highlights.exploreMore': 'Daha Fazla Keşfet',
    
    'index.whyChoose': 'Neden Bizi Seçmelisiniz',
    'index.excellence': 'Her Gösteride Mükemmellik',
    'index.excellenceDescription': 'Pan Productions\'ı Londra tiyatro sahnesinde öncü bir isim yapan özellikleri keşfedin',
    
    'index.feature.award.title': 'Ödüllü Prodüksiyonlar',
    'index.feature.award.description': 'Birçok tiyatro ödülü ve eleştirmen beğenisiyle tanınan mükemmel yapımlar',
    'index.feature.cast.title': 'Uzman Kadro & Ekip',
    'index.feature.cast.description': 'Yılların deneyimi ve tutkusuyla donanmış yetenekli profesyoneller',
    'index.feature.community.title': 'Büyüyen Topluluk',
    'index.feature.community.description': 'Binlerce tiyatro severi ve gelecek vaat eden sanatçıya katılın',
    'index.feature.passion.title': 'Tiyatro Tutkusu',
    'index.feature.passion.description': 'Güçlü hikayeleri ve performansları sahneye taşımaya adanmışlık',
    
    'index.featured': 'Şu Anda Sahnede',
    'index.featuredTitle': 'Öne Çıkan Prodüksiyonlar',
    'index.featuredDescription': 'Güncel tiyatro gösterilerimizi deneyimleyin',
    'index.featured.earnest.title': 'Ciddi Olmanın Önemi',
    'index.featured.earnest.subtitle': 'Bir Görgü Komedisi',
    'index.featured.earnest.status': 'Şimdi Sahnede',
    'index.featured.earnest.description': 'Oscar Wilde\'ın efsanevi eseri Pan Productions\'ın beğenilen kadrosuyla sahneye dönüyor.',
    'index.featured.workshop.title': 'Yaz Tiyatro Atölyesi',
    'index.featured.workshop.subtitle': 'Yoğun Drama Kursu',
    'index.featured.workshop.status': 'Kayıtlar Başladı',
    'index.featured.workshop.description': 'Kapsamlı atölyemize katılın ve sektör profesyonellerinden öğrenin.',
    'index.reviews': 'Değerlendirme',
    'index.learnMore': 'Detaylı Bilgi',
    'index.bookNow': 'Hemen Rezervasyon',
    'index.viewAll': 'Tüm Prodüksiyonları Görüntüle',
    
    'index.testimonials': 'Görüşler',
    'index.testimonialsTitle': 'Katılımcılarımız Ne Diyor',
    'index.testimonialsDescription': 'İzleyicilerimizden ve öğrencilerimizden deneyimlerini dinleyin',
    'index.testimonial1.name': 'Sarah Mitchell',
    'index.testimonial1.role': 'Tiyatro Sever',
    'index.testimonial1.content': 'Pan Productions sürekli olarak olağanüstü performanslar sunuyor. Detaylara gösterilen özen ve oyuncuların tutkusu gerçekten etkileyici.',
    'index.testimonial2.name': 'James Wilson',
    'index.testimonial2.role': 'Atölye Katılımcısı',
    'index.testimonial2.content': 'Atölyeler oyunculuk becerilerimi tamamen değiştirdi. Eğitmenler bilgili, destekleyici ve gelişiminize gerçekten önem veriyorlar.',
    'index.testimonial3.name': 'Emily Thompson',
    'index.testimonial3.role': 'Düzenli Katılımcı',
    'index.testimonial3.content': 'Her prodüksiyon bir başyapıt. Pan Productions Londra\'da en çok tercih ettiğim tiyatro topluluğu oldu.',
    
    'index.cta.title': 'Büyüyü Yaşamaya Hazır Mısınız?',
    'index.cta.description': 'Unutulmaz bir tiyatro deneyimi için bize katılın. Hemen biletinizi alın veya oyunculuk yolculuğunuza başlamak için atölyelerimizi keşfedin.',
    'index.cta.bookTickets': 'Bilet Satın Al',
    'index.cta.exploreWorkshops': 'Atölyeleri Keşfet',
    
    // Newsletter
    'newsletter.title': 'Güncel Kalın',
    'newsletter.description': 'Yaklaşan prodüksiyonlar, atölye duyuruları ve sahne arkası içerikleri hakkında özel güncellemeleri doğrudan e-postanıza alın.',
    'newsletter.placeholder': 'E-posta adresinizi girin',
    'newsletter.subscribe': 'Abone Ol',
    'newsletter.subscribing': 'Abone olunuyor...',
    'newsletter.noSpam': 'Spam yok. İstediğiniz zaman abonelikten çıkabilirsiniz.',
    'newsletter.success': 'Pan Productions\'a Hoş Geldiniz!',
    'newsletter.successMessage': 'Bültenimize başarıyla abone oldunuz.',
    
    // News Page
    'news.title1': 'Son',
    'news.title2': 'Haberler & Basın',
    'news.subtitle': 'En son duyurularımız, eleştirilerimiz ve basın haberlerimizle güncel kalın',
    
    // Footer
    'footer.tagline': 'Olağanüstü tiyatro ile hikayelere hayat veriyoruz',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.contact': 'İletişim',
    'footer.followUs': 'Bizi Takip Edin',
    'footer.rights': 'Tüm hakları saklıdır.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'TR' ? 'TR' : 'EN') as Language;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
