import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'TR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Navigation
    'nav.productions': 'Productions',
    'nav.marketing': 'PR & Marketing',
    'nav.academy': 'Pan Academy',
    'nav.workshops': 'Workshops',
    'nav.lessons': 'Lessons',
    'nav.about': 'About Us',
    'nav.news': 'News & Press',
    'nav.contact': 'Contact Us',
    'nav.getInvolved': 'Get Involved',
    
    // Hero Section
    'hero.slide1.title': 'Bringing Stories to Life on Stage',
    'hero.slide1.subtitle': 'Productions & Experience',
    'hero.slide1.description': 'Experience unforgettable theater productions with Pan Productions.',
    'hero.slide1.cta': 'See Upcoming Shows',
    
    'hero.slide2.title': 'Promoting Stories Beyond the Stage',
    'hero.slide2.subtitle': 'PR & Marketing',
    'hero.slide2.description': 'Our PR and marketing team ensures every production reaches the audience it deserves.',
    'hero.slide2.cta': 'Learn About Our PR Services',
    
    'hero.slide3.title': 'Empowering Creativity Through Pan Academy',
    'hero.slide3.subtitle': 'Pan Academy Workshops',
    'hero.slide3.description': 'Our workshops inspire and nurture the next generation of performers.',
    'hero.slide3.cta': 'Join a Workshop',
    
    // Index Page
    'index.whatWeOffer': 'What We Offer',
    'index.discover': 'Discover Pan Productions',
    'index.discoverDescription': 'From professional theatre productions to comprehensive drama education, we bring stories to life and nurture the next generation of performers.',
    
    'index.highlights.productions.title': 'Current Productions',
    'index.highlights.productions.description': 'Experience our acclaimed theatrical performances featuring talented casts and captivating stories.',
    'index.highlights.academy.title': 'Pan Academy',
    'index.highlights.academy.description': 'Professional workshops and lessons for actors of all levels, taught by industry experts.',
    'index.highlights.news.title': 'News & Press',
    'index.highlights.news.description': 'Stay updated with our latest news, reviews, and press coverage from the theatre world.',
    'index.highlights.exploreMore': 'Explore More',
    
    'index.whyChoose': 'Why Choose Us',
    'index.excellence': 'Excellence in Every Performance',
    'index.excellenceDescription': 'Discover what makes Pan Productions a leading name in London\'s theatre scene',
    
    'index.feature.award.title': 'Award-Winning Productions',
    'index.feature.award.description': 'Recognized for excellence with multiple theatre awards and critical acclaim',
    'index.feature.cast.title': 'Expert Cast & Crew',
    'index.feature.cast.description': 'Talented professionals with years of industry experience and passion',
    'index.feature.community.title': 'Growing Community',
    'index.feature.community.description': 'Join thousands of theatre enthusiasts and aspiring performers',
    'index.feature.passion.title': 'Passion for Theatre',
    'index.feature.passion.description': 'Dedicated to bringing powerful stories and performances to life',
    
    'index.featured': 'On Stage Now',
    'index.featuredTitle': 'Featured Productions',
    'index.featuredDescription': 'Experience our current theatrical performances',
    'index.featured.earnest.title': 'The Importance of Being Earnest',
    'index.featured.earnest.subtitle': 'A Comedy of Manners',
    'index.featured.earnest.status': 'Now Playing',
    'index.featured.earnest.description': 'Oscar Wilde\'s brilliant masterpiece returns with Pan Productions\' acclaimed cast.',
    'index.featured.workshop.title': 'Summer Theatre Workshop',
    'index.featured.workshop.subtitle': 'Intensive Drama Course',
    'index.featured.workshop.status': 'Enrolling Now',
    'index.featured.workshop.description': 'Join our immersive workshop and learn from industry professionals.',
    'index.reviews': 'Reviews',
    'index.learnMore': 'Learn More',
    'index.bookNow': 'Book Now',
    'index.viewAll': 'View All Productions',
    
    'index.testimonials': 'Testimonials',
    'index.testimonialsTitle': 'Testimonials',
    'index.testimonialsDescription': 'Hear from our audience and students about their experiences',
    'index.testimonial1.name': 'Sarah Mitchell',
    'index.testimonial1.role': 'Theatre Enthusiast',
    'index.testimonial1.content': 'Pan Productions consistently delivers outstanding performances. The attention to detail and passion of the cast is remarkable.',
    'index.testimonial2.name': 'James Wilson',
    'index.testimonial2.role': 'Workshop Student',
    'index.testimonial2.content': 'The workshops transformed my acting skills. The instructors are knowledgeable, supportive, and truly invested in your growth.',
    'index.testimonial3.name': 'Emily Thompson',
    'index.testimonial3.role': 'Regular Attendee',
    'index.testimonial3.content': 'Every production is a masterpiece. Pan Productions has become my go-to theatre company in London.',
    
    'index.cta.title': 'Ready to Experience the Magic?',
    'index.cta.description': 'Join us for an unforgettable theatrical experience. Book your tickets now or explore our workshops to start your acting journey.',
    'index.cta.bookTickets': 'Book Tickets',
    'index.cta.exploreWorkshops': 'Explore Workshops',
    
    // Newsletter
    'newsletter.title': 'Stay in the Spotlight',
    'newsletter.description': 'Get exclusive updates on upcoming productions, workshop announcements, and behind-the-scenes content delivered straight to your inbox.',
    'newsletter.placeholder': 'Enter your email address',
    'newsletter.subscribe': 'Subscribe',
    'newsletter.subscribing': 'Subscribing...',
    'newsletter.noSpam': 'No spam. Unsubscribe anytime.',
    'newsletter.success': 'Welcome to Pan Productions!',
    'newsletter.successMessage': 'You\'ve successfully subscribed to our newsletter.',
    
    // Footer
    'footer.tagline': 'Bringing stories to life through exceptional theatre',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
  },
  TR: {
    // Navigation
    'nav.productions': 'Prodüksiyonlar',
    'nav.marketing': 'PR & Pazarlama',
    'nav.academy': 'Pan Akademi',
    'nav.workshops': 'Atölyeler',
    'nav.lessons': 'Dersler',
    'nav.about': 'Hakkımızda',
    'nav.news': 'Haberler & Basın',
    'nav.contact': 'İletişim',
    'nav.getInvolved': 'Bize Katılın',
    
    // About Page
    'about.founded': '2016 Yılında Kuruldu',
    'about.heroTitle': 'Biz Kimiz?',
    'about.heroSubtitle': 'Türk kültürünü ve sanatını İngiltere izleyicilerine olağanüstü performanslar ve kültürel işbirlikleri yoluyla taşımaya adanmış, canlı ve bağımsız bir tiyatro prodüksiyon şirketi.',
    'about.historyTitle': 'Tarihçe',
    'about.historyP1': 'Pan Productions (PP), Londra merkezli, canlı ve bağımsız bir tiyatro prodüksiyon şirketidir. Şirket, uluslararası çapta tanınmış Türk oyuncular, sanatçılar ve müzisyenleri içeren Türkçe prodüksiyonları İngiltere izleyicilerine sunmaya kendini adamıştır.',
    'about.historyP2': 'Kasım 2016\'da tiyatro yapımcısı Zeynep Dalkıran tarafından kurulan PP, Türkçe tiyatroda on yılı aşkın deneyimden doğdu. Zeynep, ticari ve ticari olmayan prodüksiyonlardaki -tiyatro, sanat sergileri ve konserler- kapsamlı geçmişini birleştirerek Türk kültürünü Londra sahnesinde kutlayan ve yükselten bir şirket yarattı.',
    'about.historyP3': 'Pan Productions, ulusal ve uluslararası düzeyde olağanüstü performanslar üretmeyi ve ortak üretmeyi amaçlarken, diğer tiyatro şirketlerine de en kaliteli prodüksiyon hizmetleri sunmaktadır. Yerel organizatörler ve küresel ortaklarla işbirliği yaparak, PP kültürel köprüler kurmaya ve Türk sanatı, müziği ve tiyatrosunun zenginliğini çeşitli izleyicilere taşımaya devam ediyor.',
    'about.missionTitle': 'Misyonumuz',
    'about.missionP1': 'Pan Productions\'ın misyonu, Londra\'da önde gelen Türkçe kültürel etkinlikler üretmek, konserleri, oyunları ve sergileri aracılığıyla en iyi oyuncuları, sanatçıları ve müzisyenleri bir araya getirmektir. Türk sanatının zenginliğini sergileyen ve İngiltere\'deki çeşitli izleyicilerle bağlantı kuran dünya standartlarında prodüksiyonlar yaratmaya adanmışız.',
    'about.missionP2': 'Ana prodüksiyonlarımıza ek olarak, Pan Productions bir dizi tamamlayıcı etkinlik sunmaktadır - samimi oturum sezonları, tiyatro turları, mekana özel performanslar ve tek gecelik özel etkinlikler dahil. Ayrıca araştırma, danışmanlık ve lojistik planlama hizmetleri sağlayarak, kültürel ve sanatsal projeleri gelişimin tüm aşamalarında destekliyoruz.',
    'about.visionTitle': 'Vizyonumuz',
    'about.visionP1': 'Vizyonumuz, yalnızca yerleşik Türkçe prodüksiyonları (Türkiye\'de kanıtlanmış ve kutlanmış) desteklemek ve finanse etmek değil, aynı zamanda orijinal eserler geliştirmek ve bunları Londra\'daki Türkçe konuşan topluluk için prömiyerini yapmaktır.',
    'about.visionP2': 'Bugün, ana odak noktamız tiyatro dünyasında yatıyor - sahnede yaratılabilecek drama ve performansın tüm yelpazesini kucaklayarak. Londra merkezli bir prodüksiyon şirketi olarak, Pan Productions her geçmişten insanları bir araya getirmeyi, gösteri sanatları aracılığıyla işbirliği, kapsayıcılık ve kültürel alışverişi teşvik etmeyi amaçlamaktadır.',
    'about.valuesTitle': 'Değerlerimiz',
    'about.valuesSubtitle': 'Yaptığımız her şeye rehberlik eden ilkeler',
    'about.value1Title': 'Kültürel Mükemmellik',
    'about.value1Description': 'Dünya standartlarında prodüksiyonlar aracılığıyla Türk sanatı ve kültürünün zenginliğini Londra izleyicilerine sunmak.',
    'about.value2Title': 'Kapsayıcı İşbirliği',
    'about.value2Description': 'Gösteri sanatları aracılığıyla her geçmişten insanları bir araya getirmek ve işbirliğini teşvik etmek.',
    'about.value3Title': 'Uluslararası Köprü',
    'about.value3Description': 'Olağanüstü tiyatro gösterileri aracılığıyla Türkiye ve İngiltere arasında kültürel köprüler kurmak.',
    'about.value4Title': 'Orijinal Eserler',
    'about.value4Description': 'Türkçe konuşan toplulukları kutlayan orijinal prodüksiyonlar yaratmak ve prömiyerini yapmak.',
    'about.testimonialsTitle': 'Görüşler',
    'about.testimonialsSubtitle': 'İzleyicilerimizden ve atölye katılımcılarından değerlendirmeler ve yorumlar',
    'about.testimonial1': '...pek çok \'geleneksel\' oyun versiyonundan sonra, taze bir bakış açısı fazlasıyla hoş karşılanıyor.',
    'about.testimonial1Source': '— Theatre Things',
    'about.testimonial2': 'Harikaydı! Aradığım her şeyi buldum.',
    'about.testimonial2Source': '— Devised Theatre Atölyesi Katılımcısı',
    'about.testimonial3': '...onu yeniden canlandırdı ve sanki dün yazılmış gibi hissettirdi. Çok yaratıcı ve zeki.',
    'about.testimonial3Source': '— The Importance of Being Earnest İzleyici Yorumu',
    
    // Contact Page
    'contact.title': 'İletişim',
    'contact.subtitle': 'Sizden haber almak isteriz. Bize mesaj gönderin, en kısa sürede yanıt verelim.',
    'contact.firstName': 'Ad',
    'contact.firstNamePlaceholder': 'Adınızı girin',
    'contact.lastName': 'Soyad',
    'contact.lastNamePlaceholder': 'Soyadınızı girin',
    'contact.email': 'E-posta Adresi',
    'contact.emailPlaceholder': 'E-posta adresinizi girin',
    'contact.phone': 'Telefon Numarası (İsteğe Bağlı)',
    'contact.phonePlaceholder': 'Telefon numaranızı girin',
    'contact.subject': 'Konu',
    'contact.subjectPlaceholder': 'Bu nedir?',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Size nasıl yardımcı olabileceğimizi anlatın...',
    'contact.sending': 'Gönderiliyor...',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.messageSent': 'Mesaj Gönderildi! 🎉',
    'contact.messageSuccess': 'Teşekkürler {name}! Mesajınız gönderildi. En kısa sürede size geri döneceğiz.',
    'contact.error': 'Hata',
    'contact.errorMessage': 'Üzgünüz, mesajınızı gönderirken bir hata oluştu. Lütfen tekrar deneyin veya doğrudan panproductionsuk@gmail.com adresine e-posta gönderin',
    'contact.faqTitle': 'Sıkça Sorulan Sorular',
    'contact.faqSubtitle': 'Sık sorulan sorulara hızlı yanıtlar',
    'contact.faq1Question': 'Pan Productions gösterilerine nasıl seçme yapabilirim?',
    'contact.faq1Answer': 'Seçme bilgileri Prodüksiyonlar sayfamızda ve sosyal medyada yayınlanır. Genellikle her prodüksiyon provalarına başlamadan 6-8 hafta önce açık seçmeler düzenliyoruz.',
    'contact.faq2Question': 'Yaklaşan gösteriler ve atölyeler hakkında nasıl güncel kalabilirim?',
    'contact.faq2Answer': 'Bültenimize abone olun, bizi sosyal medyada takip edin ve en son gösteri duyuruları ve bilet bilgileri için web sitemizi düzenli olarak kontrol edin.',
    'contact.faq3Question': 'Atölyeleriniz için giriş gereksinimleri nelerdir?',
    'contact.faq3Answer': 'Tek gereksimimiz coşku ve tiyatroya ilgidir. Önceki eğitim gerekli değildir.',
    'contact.faq4Question': 'Yazdığım orijinal bir eseri sahneleyebilir miyim?',
    'contact.faq4Answer': 'Kesinlikle! hello@panproductions.co.uk adresinden bize ulaşın ve ekibimiz konuları daha fazla görüşmek için sizinle iletişime geçecektir.',
    
    // Marketing Page
    'marketing.heroTitle': 'PR & Pazarlama Mükemmelliği',
    'marketing.heroSubtitle': 'Yaratıcı Vizyonunuzu Güçlendirin',
    'marketing.heroDescription': 'Pan Productions, tiyatro, müzik ve sergilerde proje bazında özel PR & Pazarlama stratejileri ve destek sağlar.',
    'marketing.getInTouch': 'İletişime Geçin',
    'marketing.description': 'Pan Productions, tiyatro, müzik ve sergilerde proje bazında özel PR & Pazarlama stratejileri ve destek sağlar.',
    'marketing.service1Title': 'Stratejik Pazarlama',
    'marketing.service1Description': 'Prodüksiyonunuzun benzersiz ihtiyaçlarına ve hedef kitlesine özel kapsamlı pazarlama stratejileri.',
    'marketing.service1Feature1': 'Pazar Araştırması',
    'marketing.service1Feature2': 'İzleyici Analizi',
    'marketing.service1Feature3': 'Marka Konumlandırma',
    'marketing.service1Feature4': 'Kampanya Planlama',
    'marketing.service2Title': 'Halkla İlişkiler',
    'marketing.service2Description': 'Prodüksiyonunuzun görünürlüğünü ve medya kapsamını en üst düzeye çıkarmak için profesyonel PR hizmetleri.',
    'marketing.service2Feature1': 'Basın Bültenleri',
    'marketing.service2Feature2': 'Medya İlişkileri',
    'marketing.service2Feature3': 'Röportaj Koordinasyonu',
    'marketing.service2Feature4': 'Kriz Yönetimi',
    'marketing.service3Title': 'İçerik Oluşturma',
    'marketing.service3Description': 'Fotoğrafçılık, videografi ve grafik tasarım dahil yüksek kaliteli tanıtım içeriği.',
    'marketing.service3Feature1': 'Profesyonel Fotoğrafçılık',
    'marketing.service3Feature2': 'Video Prodüksiyonu',
    'marketing.service3Feature3': 'Grafik Tasarım',
    'marketing.service3Feature4': 'Sosyal Medya İçeriği',
    'marketing.service4Title': 'Dijital Pazarlama',
    'marketing.service4Description': 'Tüm çevrimiçi platformlarda izleyicilere ulaşmak için eksiksiz dijital pazarlama çözümleri.',
    'marketing.service4Feature1': 'Sosyal Medya Pazarlaması',
    'marketing.service4Feature2': 'Web Sitesi Geliştirme',
    'marketing.service4Feature3': 'SEO Optimizasyonu',
    'marketing.service4Feature4': 'E-posta Kampanyaları',
    'marketing.ctaTitle': 'Prodüksiyonunuzu Tanıtmaya Hazır Mısınız?',
    
    // Productions Page
    'productions.title': 'Prodüksiyonlar',
    'productions.subtitle': 'Geçmiş, güncel ve gelecek tiyatro prodüksiyonlarımızı keşfedin',
    'productions.tabCurrent': 'Güncel',
    'productions.tabUpcoming': 'Yaklaşan',
    'productions.tabPast': 'Geçmiş',
    'productions.by': 'yazan',
    'productions.buyTickets': 'Bilet Satın Al',
    'productions.comingSoon': 'Çok Yakında',
    'productions.archive': 'Arşiv',
    'productions.statusCurrent': 'Şimdi Sahnede',
    'productions.statusUpcoming': 'Yakında',
    'productions.statusPast': 'Geçmiş',
    
    // Workshops Page
    'workshops.title': 'Atölyeler',
    'workshops.subtitle': 'Her yaştan ve seviyeden katılımcı için kapsamlı tiyatro atölyeleri',
    'workshops.tabTheater': 'Tiyatro',
    'workshops.tabMusic': 'Müzik',
    'workshops.tabArt': 'Sanat',
    'workshops.tabFilm': 'Film',
    'workshops.level': 'Seviye',
    'workshops.duration': 'Süre',
    'workshops.schedule': 'Program',
    'workshops.instructor': 'Eğitmen',
    'workshops.price': 'Fiyat',
    'workshops.enrollNow': 'Şimdi Kaydol',
    'workshops.learnMore': 'Daha Fazla Bilgi',
    'workshops.noWorkshops': 'Şu anda bu kategoride atölye bulunmamaktadır. Yeni atölyeler için yakında tekrar kontrol edin!',
    
    // Get Involved Page
    'getInvolved.title': 'Bize Katılın',
    'getInvolved.subtitle': 'Farklı yollarla Pan Productions\'ın misyonuna katkıda bulunun',
    'getInvolved.donateTitle': 'Bağış Yapın',
    'getInvolved.donateSubtitle': 'Misyonumuzu Destekleyin',
    'getInvolved.donateDescription': 'Güçlü tiyatro deneyimleri yaratmaya ve topluluğumuza sanat eğitimi sağlamaya devam etmemize yardımcı olun.',
    'getInvolved.donateFeature1': 'Yeni prodüksiyonları destekleyin',
    'getInvolved.donateFeature2': 'Eğitim programlarını fonlayın',
    'getInvolved.donateFeature3': 'Burs sağlayın',
    'getInvolved.donateFeature4': 'Tesislerimizi sürdürün',
    'getInvolved.donateCta': 'Bağış Yapın',
    'getInvolved.volunteerTitle': 'Gönüllü Olun',
    'getInvolved.volunteerSubtitle': 'Ekibimize Katılın',
    'getInvolved.volunteerDescription': 'Yaratıcı topluluğumuzun bir parçası olun ve profesyonel tiyatro prodüksiyonunda uygulamalı deneyim kazanın.',
    'getInvolved.volunteerFeature1': 'Prodüksiyon yardımı',
    'getInvolved.volunteerFeature2': 'Etkinlik yönetimi',
    'getInvolved.volunteerFeature3': 'Pazarlama desteği',
    'getInvolved.volunteerFeature4': 'İdari yardım',
    'getInvolved.volunteerCta': 'Gönüllü Başvurusu',
    'getInvolved.partnerTitle': 'Ortak Olun',
    'getInvolved.partnerSubtitle': 'Kurumsal İşbirliği',
    'getInvolved.partnerDescription': 'İşiniz ile sanat topluluğu arasında anlamlı bağlantılar oluşturmak için bizimle ortak olun.',
    'getInvolved.partnerFeature1': 'Marka görünürlüğü',
    'getInvolved.partnerFeature2': 'Topluluk katılımı',
    'getInvolved.partnerFeature3': 'Çalışan avantajları',
    'getInvolved.partnerFeature4': 'Ağ oluşturma fırsatları',
    'getInvolved.partnerCta': 'Ortaklık Talebi',
    'getInvolved.volunteerRolesTitle': 'Gönüllü Rolleri',
    'getInvolved.volunteerRolesSubtitle': 'Aramıza katılmanın çeşitli yollarını keşfedin',
    'getInvolved.role1Title': 'Prodüksiyon Asistanı',
    'getInvolved.role1Commitment': 'Haftada 10-15 saat',
    'getInvolved.role1Description': 'Prodüksiyon ekibimize sahne arkası operasyonları, set inşaatı ve teknik destek konularında yardımcı olun.',
    'getInvolved.role1Skill1': 'Güvenilirlik',
    'getInvolved.role1Skill2': 'Fiziksel yetenek',
    'getInvolved.role1Skill3': 'Takım oyuncusu',
    'getInvolved.role2Title': 'Pazarlama Gönüllüsü',
    'getInvolved.role2Commitment': 'Haftada 5-8 saat',
    'getInvolved.role2Description': 'Sosyal medya, içerik oluşturma ve topluluk erişimi yoluyla prodüksiyonlarımızı tanıtmaya yardımcı olun.',
    'getInvolved.role2Skill1': 'Sosyal medya',
    'getInvolved.role2Skill2': 'Yazma',
    'getInvolved.role2Skill3': 'Fotoğrafçılık',
    'getInvolved.role3Title': 'Etkinlik Koordinatörü',
    'getInvolved.role3Commitment': 'Haftada 8-12 saat',
    'getInvolved.role3Description': 'Özel etkinlikler, atölyeler ve topluluk katılım faaliyetlerinin organizasyonunda yardımcı olun.',
    'getInvolved.role3Skill1': 'Organizasyon',
    'getInvolved.role3Skill2': 'İletişim',
    'getInvolved.role3Skill3': 'Etkinlik planlama',
    'getInvolved.role4Title': 'Eğitim Desteği',
    'getInvolved.role4Commitment': 'Haftada 6-10 saat',
    'getInvolved.role4Description': 'Her yaştan öğrenci için Pan Akademi atölyeleri ve eğitim programlarına destek olun.',
    'getInvolved.role4Skill1': 'Sabır',
    'getInvolved.role4Skill2': 'Öğretme ilgisi',
    'getInvolved.role4Skill3': 'Sanat altyapısı',
    'getInvolved.partnershipBenefitsTitle': 'Ortaklık Seviyeleri',
    'getInvolved.partnershipBenefitsSubtitle': 'Her bütçeye uygun esnek ortaklık seçenekleri',
    'getInvolved.partnerLevel1': 'Destekleyen Ortak',
    'getInvolved.partnerLevel1Amount': '£1.000 - £2.500',
    'getInvolved.partnerLevel1Benefit1': 'Programlarda logo',
    'getInvolved.partnerLevel1Benefit2': 'Sosyal medya anonsları',
    'getInvolved.partnerLevel1Benefit3': 'Gösteri başına 2 ücretsiz bilet',
    'getInvolved.partnerLevel2': 'Ana Ortak',
    'getInvolved.partnerLevel2Amount': '£2.500 - £5.000',
    'getInvolved.partnerLevel2Benefit1': 'Tüm pazarlama materyallerinde logo',
    'getInvolved.partnerLevel2Benefit2': 'Prömiyere VIP davetler',
    'getInvolved.partnerLevel2Benefit3': 'Gösteri başına 4 ücretsiz bilet',
    'getInvolved.partnerLevel3': 'Öncü Ortak',
    'getInvolved.partnerLevel3Amount': '£5.000+',
    'getInvolved.partnerLevel3Benefit1': 'Özel prodüksiyon sponsorluğu',
    'getInvolved.partnerLevel3Benefit2': 'Özel etkinlikler ve tanışmalar',
    'getInvolved.partnerLevel3Benefit3': 'Sezon için sınırsız bilet',
    'getInvolved.impactTitle': 'Etkimiz',
    'getInvolved.impactSubtitle': 'Desteğiniz gerçek fark yaratıyor',
    'getInvolved.impact1Title': 'Öğrencilere Ulaşıldı',
    'getInvolved.impact1Description': 'Ücretsiz atölye programlarımız aracılığıyla',
    'getInvolved.impact2Title': 'Prodüksiyon Finanse Edildi',
    'getInvolved.impact2Description': 'Geçen yıl bağışlarla',
    'getInvolved.impact3Title': 'Gönüllü Saat',
    'getInvolved.impact3Description': 'Topluluk üyelerinden katkı',
    'getInvolved.impact4Title': 'Burs Sağlandı',
    'getInvolved.impact4Description': 'Tutkulu öğrencilere',
    'getInvolved.ctaTitle': 'Aramıza Katılmaya Hazır Mısınız?',
    'getInvolved.ctaDescription': 'İşinizi nasıl dahil etmek isterseniz edin, her katkı önemlidir. Bugün bizimle iletişime geçin.',
    'getInvolved.commitment': 'Sorumluluk',
    'getInvolved.skills': 'Beceriler',
    'getInvolved.benefits': 'Avantajlar',
    
    // Hero Section
    'hero.slide1.title': 'Hikayelere Sahnede Hayat Veriyoruz',
    'hero.slide1.subtitle': 'Prodüksiyonlar & Deneyim',
    'hero.slide1.description': 'Pan Productions ile unutulmaz tiyatro prodüksiyonlarını yaşayın.',
    'hero.slide1.cta': 'Yaklaşan Gösterileri İnceleyin',
    
    'hero.slide2.title': 'Hikayelerimizi Sahnenin Ötesine Taşıyoruz',
    'hero.slide2.subtitle': 'PR & Pazarlama',
    'hero.slide2.description': 'PR ve pazarlama ekibimiz, her prodüksiyonun hak ettiği izleyiciye ulaşmasını sağlar.',
    'hero.slide2.cta': 'PR Hizmetlerimizi Keşfedin',
    
    'hero.slide3.title': 'Pan Akademi ile Yaratıcılığa Güç Veriyoruz',
    'hero.slide3.subtitle': 'Pan Akademi Atölyeleri',
    'hero.slide3.description': 'Atölyelerimiz gelecek nesil sanatçılara ilham verir ve onları geliştirir.',
    'hero.slide3.cta': 'Atölyelere Katılın',
    
    // Index Page
    'index.whatWeOffer': 'Neler Sunuyoruz',
    'index.discover': 'Pan Productions\'ı Keşfedin',
    'index.discoverDescription': 'Profesyonel tiyatro prodüksiyonlarından kapsamlı drama eğitimine kadar, hikayelere hayat veriyoruz ve gelecek nesil sanatçıları yetiştiriyoruz.',
    
    'index.highlights.productions.title': 'Güncel Prodüksiyonlar',
    'index.highlights.productions.description': 'Yetenekli oyuncu kadrosu ve büyüleyici hikayeleriyle dikkat çeken tiyatro gösterilerimizi deneyimleyin.',
    'index.highlights.academy.title': 'Pan Akademi',
    'index.highlights.academy.description': 'Her seviyeden oyuncu için, sektör uzmanları tarafından verilen profesyonel atölyeler ve dersler.',
    'index.highlights.news.title': 'Haberler & Basın',
    'index.highlights.news.description': 'En son haberlerimiz, eleştirilerimiz ve tiyatro dünyasından basın haberlerimizle güncel kalın.',
    'index.highlights.exploreMore': 'Daha Fazla Keşfet',
    
    'index.whyChoose': 'Neden Bizi Seçmelisiniz',
    'index.excellence': 'Her Gösteride Mükemmellik',
    'index.excellenceDescription': 'Pan Productions\'ı Londra tiyatro sahnesinde öncü bir isim yapan özellikleri keşfedin',
    
    'index.feature.award.title': 'Ödüllü Prodüksiyonlar',
    'index.feature.award.description': 'Birçok tiyatro ödülü ve eleştirmen beğenisiyle tanınan mükemmel yapımlar',
    'index.feature.cast.title': 'Uzman Kadro & Ekip',
    'index.feature.cast.description': 'Yılların deneyimi ve tutkusuyla donanmış yetenekli profesyoneller',
    'index.feature.community.title': 'Büyüyen Topluluk',
    'index.feature.community.description': 'Binlerce tiyatro severi ve gelecek vaat eden sanatçıya katılın',
    'index.feature.passion.title': 'Tiyatro Tutkusu',
    'index.feature.passion.description': 'Güçlü hikayeleri ve performansları sahneye taşımaya adanmışlık',
    
    'index.featured': 'Şu Anda Sahnede',
    'index.featuredTitle': 'Öne Çıkan Prodüksiyonlar',
    'index.featuredDescription': 'Güncel tiyatro gösterilerimizi deneyimleyin',
    'index.featured.earnest.title': 'Ciddi Olmanın Önemi',
    'index.featured.earnest.subtitle': 'Bir Görgü Komedisi',
    'index.featured.earnest.status': 'Şimdi Sahnede',
    'index.featured.earnest.description': 'Oscar Wilde\'ın efsanevi eseri Pan Productions\'ın beğenilen kadrosuyla sahneye dönüyor.',
    'index.featured.workshop.title': 'Yaz Tiyatro Atölyesi',
    'index.featured.workshop.subtitle': 'Yoğun Drama Kursu',
    'index.featured.workshop.status': 'Kayıtlar Başladı',
    'index.featured.workshop.description': 'Kapsamlı atölyemize katılın ve sektör profesyonellerinden öğrenin.',
    'index.reviews': 'Değerlendirme',
    'index.learnMore': 'Detaylı Bilgi',
    'index.bookNow': 'Hemen Rezervasyon',
    'index.viewAll': 'Tüm Prodüksiyonları Görüntüle',
    
    'index.testimonials': 'Görüşler',
    'index.testimonialsTitle': 'Katılımcılarımız Ne Diyor',
    'index.testimonialsDescription': 'İzleyicilerimizden ve öğrencilerimizden deneyimlerini dinleyin',
    'index.testimonial1.name': 'Sarah Mitchell',
    'index.testimonial1.role': 'Tiyatro Sever',
    'index.testimonial1.content': 'Pan Productions sürekli olarak olağanüstü performanslar sunuyor. Detaylara gösterilen özen ve oyuncuların tutkusu gerçekten etkileyici.',
    'index.testimonial2.name': 'James Wilson',
    'index.testimonial2.role': 'Atölye Katılımcısı',
    'index.testimonial2.content': 'Atölyeler oyunculuk becerilerimi tamamen değiştirdi. Eğitmenler bilgili, destekleyici ve gelişiminize gerçekten önem veriyorlar.',
    'index.testimonial3.name': 'Emily Thompson',
    'index.testimonial3.role': 'Düzenli Katılımcı',
    'index.testimonial3.content': 'Her prodüksiyon bir başyapıt. Pan Productions Londra\'da en çok tercih ettiğim tiyatro topluluğu oldu.',
    
    'index.cta.title': 'Büyüyü Yaşamaya Hazır Mısınız?',
    'index.cta.description': 'Unutulmaz bir tiyatro deneyimi için bize katılın. Hemen biletinizi alın veya oyunculuk yolculuğunuza başlamak için atölyelerimizi keşfedin.',
    'index.cta.bookTickets': 'Bilet Satın Al',
    'index.cta.exploreWorkshops': 'Atölyeleri Keşfet',
    
    // Newsletter
    'newsletter.title': 'Güncel Kalın',
    'newsletter.description': 'Yaklaşan prodüksiyonlar, atölye duyuruları ve sahne arkası içerikleri hakkında özel güncellemeleri doğrudan e-postanıza alın.',
    'newsletter.placeholder': 'E-posta adresinizi girin',
    'newsletter.subscribe': 'Abone Ol',
    'newsletter.subscribing': 'Abone olunuyor...',
    'newsletter.noSpam': 'Spam yok. İstediğiniz zaman abonelikten çıkabilirsiniz.',
    'newsletter.success': 'Pan Productions\'a Hoş Geldiniz!',
    'newsletter.successMessage': 'Bültenimize başarıyla abone oldunuz.',
    
    // Footer
    'footer.tagline': 'Olağanüstü tiyatro ile hikayelere hayat veriyoruz',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.contact': 'İletişim',
    'footer.followUs': 'Bizi Takip Edin',
    'footer.rights': 'Tüm hakları saklıdır.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'TR' ? 'TR' : 'EN') as Language;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
